"""empty message

Revision ID: 545482d2e686
Revises: 
Create Date: 2022-09-30 14:54:48.997417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545482d2e686'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medicine')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medicine',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('medicine_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rate', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='medicine_pkey')
    )
    # ### end Alembic commands ###
